<?php

namespace NLK\MyMoneyBundle\Repository;

/**
 * ExerciceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findExerciceCourant()
	{
		$qb = $this->createQueryBuilder('a');
		$qb
			->where('a.annee = :annee')
				->setParameter('annee', date('Y'))
			->andWhere('a.mois = :mois')
				->setParameter('mois', date('m'))
		;

  		return $qb
    		->getQuery()
    		->getSingleResult()
  		;
	}

	public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

   	public function getListExercices()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->orderBy('a.id','DESC');

        return $qb;
    }
}
