<?php

namespace NLK\MyMoneyBundle\Repository;

/**
 * RentreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentreeRepository extends \Doctrine\ORM\EntityRepository
{
}
